
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tantra-Re-Source 
email: sigi@tantra-re-source.com
description: > # this means to ignore newlines until "baseurl:"
  Siegfried Présent is een tantra instructeur en tantra wellness masseur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tantra-re-source.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings

theme: 
markdown: kramdown
destination: public
exclude: ["Rakefile", "README.md", "public", "jekyll", "Gemfile", "Gemfile.lock"]

# plugins_dir:
# - jekyll-sitemap

# Multilanguage Menu - https://www.sylvaindurand.org/making-jekyll-multilingual/
t:
  nl:
    tantra:
      name: "tantra"
      url: "tantra.html"
    energetic:
      name: "energetische behandeling"
      url: "energetische_behandeling.html"
    coaching:
      name: "coaching"
      url: "coaching.html"
    workshops:
      name: "workshops"
      url: "workshops.html"
    about:
      name: "wie ben ik"
      url: "wie_ben_ik.html"
    prices:
      name: "prijzen"
      url: "prijzen.html"
  en:
    tantra:
      name: "tantra"
      url: "tantra.en.html"
    energetic:
      name: "energetic treatment"
      url: "energetic_treatment.html"
    coaching:
      name: "coaching"
      url: "coaching.en.html"
    workshops:
      name: "workshops"
      url: "workshops.en.html"
    about:
      name: "who am I"
      url: "who_am_i.html"
    prices:
      name: "prices"
      url: "prices.html"
